services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buildmanager
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
#    networks:
#      - buildmanagernetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db
#    networks:
#      - buildmanagernetwork

#  sbootapp:
#    build:
#      dockerfile: Dockerfile
#    container_name: buildmanager
#    restart: on-failure
#    depends_on:
#      - db
#    ports:
#      - '8080:8080'
#    networks:
#      - buildmanagernetwork
#    environment:
#      - "POSTGRES_HOST=db"
#
#networks:
#  buildmanagernetwork:
#    driver: bridge