/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ClientsSection: React.FC = () => {
  return (
    <section className="flex overflow-hidden flex-col items-center py-24 pr-20 pl-20 w-full bg-white bg-opacity-10 min-h-[456px] max-md:px-5 max-md:max-w-full">
      <h2 className="w-full text-4xl font-bold leading-none text-center text-white max-md:max-w-full">
        Nossos Clientes
      </h2>
      <div className="flex flex-col mt-10 max-w-full w-[1094px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e0537fe49b584c683795a56a1817dcae9700b2256a4a70c1b219dc0ef142334f?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17"
          alt="Client logos"
          className="object-contain w-full aspect-[15.63] max-md:max-w-full"
        />
      </div>
      <div className="flex flex-col mt-10 max-w-full w-[1269px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/adc493617e83b793d57a1daa77b07f5a8dcb8bcbb64312d607282f4ee434b976?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17"
          alt="More client logos"
          className="object-contain w-full aspect-[16.39] max-md:max-w-full"
        />
      </div>
    </section>
  );
};

export default ClientsSection;
