/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactInfo: React.FC = () => {
  return (
    <div className="flex flex-col items-start self-stretch my-auto min-w-[240px] w-[370px]">
      <div className="flex flex-col max-w-full w-[289px]">
        <h3 className="text-xl font-bold text-teal-700">
          Possui algum questionamento?
        </h3>
        <div className="flex gap-2 self-start mt-2 text-base text-white">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1723987cc3d32d63fa7a64199abca5f16b803e3bd81c33d01a5acfb2946075cc?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17"
            alt=""
            className="object-contain shrink-0 self-start mt-2 w-10 aspect-square"
          />
          <div className="flex flex-col">
            <a href="tel:+5527999810677">(27) 99981-0677</a>
            <a href="mailto:conarconstrutora@outlook.com" className="mt-6">
              conarconstrutora@outlook.com
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContactInfo;
