/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";

const Header: React.FC = () => {
  return (
    <header className="flex overflow-hidden flex-wrap gap-10 justify-between items-center py-8 pr-36 pl-32 w-full max-md:px-5 max-md:max-w-full">
      <Logo />
      <Navigation />
    </header>
  );
};

export default Header;
