/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <div className="flex gap-2.5 items-center self-stretch my-auto text-3xl font-semibold leading-none text-white min-w-[240px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c14c9bf60b43eedd1eb4bdf447e2e4563e580454a0aabca6d9fba017a9bfb3b7?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto aspect-[1.1] w-[45px]"
      />
      <div className="self-stretch my-auto">Conar Construtora</div>
    </div>
  );
};

export default Logo;
