/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProjectsSection: React.FC = () => {
  return (
    <section className="flex overflow-hidden flex-col justify-center px-32 pt-10 pb-24 w-full text-center text-white bg-neutral-800 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col w-full max-md:max-w-full">
        <div className="flex flex-col items-center w-full max-md:max-w-full">
          <h2 className="text-4xl font-bold leading-none">Projetos</h2>
          <p className="mt-9 text-xl leading-relaxed">
            Alguns de nossos projetos mais recentes
          </p>
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/afc35d022535e30c0bdc73932bd67830d3cc4076cd70970a56b8ee0b756ea8b7?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17"
        alt="Recent projects showcase"
        className="object-contain mt-16 w-full aspect-[2.79] max-md:mt-10 max-md:max-w-full"
      />
    </section>
  );
};

export default ProjectsSection;
