/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

interface Service {
  icon: string;
  title: string;
  description: string;
  highlighted?: boolean;
}

const services: Service[] = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a620b01fdfd95c868968e2e51fead43f93e73456538ca0be6d01febfc0df80f5?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17",
    title: "Planejamento Urbano",
    description:
      "Desenvolve e organiza áreas urbanas para crescimento sustentável.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/dcc80f8f489f1d19035573c827547b6855bd5142de3604f17d325917a234a617?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17",
    title: "Engenharia Civil",
    description:
      "Planeja, projeta e executa obras de infraestrutura com qualidade.",
    highlighted: true,
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/713bc0e2a9303fdd619f2cb9e176ed9c42f2ac8446e11caff966f414e5e2f11f?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17",
    title: "Gerenciamento de Obras",
    description:
      "Coordena prazos, recursos e qualidade para garantir entrega eficaz.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a620b01fdfd95c868968e2e51fead43f93e73456538ca0be6d01febfc0df80f5?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17",
    title: "Engenharia Eletrica",
    description:
      "Projeta sistemas elétricos eficientes para garantir segurança e uso.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e61f6080f27a25379808d407ea5694fbdc5ddf128afd84fec0a21a236197ae4f?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17",
    title: "Construção civil",
    description:
      "Realiza construções de edificações e obras para diversos setores.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/713bc0e2a9303fdd619f2cb9e176ed9c42f2ac8446e11caff966f414e5e2f11f?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17",
    title: "Engenharia Hidrossanitária",
    description:
      "Projeta soluções hidráulicas e sanitárias para eficiência e saúde.",
  },
];

const ServicesSection: React.FC = () => {
  return (
    <section className="flex flex-wrap gap-8 items-start px-32 py-24 w-full max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col grow shrink text-white min-w-[240px] w-[296px]">
        <div className="flex flex-col w-full">
          <h2 className="text-4xl font-bold leading-[50px]">
            Tenha visibilidade <br />e controle sobre <br /> seus projetos
          </h2>
          <p className="mt-10 text-xl leading-8">
            Nossos serviços oferecem uma gama de opções que prestam suporte em
            todos os processos da construção.
          </p>
        </div>
      </div>
      {services.map((service, index) => (
        <ServiceCard key={index} {...service} />
      ))}
    </section>
  );
};

export default ServicesSection;
