/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  icon: string;
  title: string;
  description: string;
  highlighted?: boolean;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  icon,
  title,
  description,
  highlighted = false,
}) => {
  const cardClass = highlighted
    ? "flex flex-col p-8 mt-8 w-full bg-teal-700 rounded-3xl shadow-[0px_10px_60px_rgba(57,131,120,0.25)] max-md:px-5"
    : "flex flex-col p-8 w-full rounded-3xl bg-white bg-opacity-10 shadow-[0px_10px_60px_rgba(153,153,153,0.07)] max-md:px-5";

  const iconClass = highlighted
    ? "flex gap-2.5 items-center p-3.5 w-16 h-16 bg-white rounded-xl"
    : "flex gap-2.5 items-center p-3.5 w-16 h-16 bg-teal-700 rounded-xl";

  return (
    <div className={cardClass}>
      <div className="flex gap-8 items-start">
        <div className={iconClass}>
          <img
            loading="lazy"
            src={icon}
            alt=""
            className="object-contain aspect-square w-[38px]"
          />
        </div>
        <h3 className="text-2xl font-bold leading-8 text-white w-[216px]">
          {title}
        </h3>
      </div>
      <p className="mt-8 text-base font-bold leading-6 text-white">
        {description}
      </p>
    </div>
  );
};

export default ServiceCard;
