/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SocialLink {
  name: string;
  url: string;
  iconSrc: string;
}

const socialLinks: SocialLink[] = [
  { name: 'Facebook', url: '#', iconSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/1619ec2b4848084a90ddbba264e0eeb4bfe0f74dc4e788650851da0bfd4d6c35?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17' },
  { name: 'Twitter', url: '#', iconSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/e9ee019f7c47acf7c9c030cf91f6a3a9ced4a8914f9b976c9b8dbeeb848185b4?placeholderIfAbsent=true&apiKey=ecff52a1287e4a56b74a437cd1dc8e17' },
  { name: 'LinkedIn', url: '#', iconSrc: 'http://b.io/'}
]
