/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import ContactInfo from "./ContactInfo";
import SocialLinks from "./SocialLinks";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col px-32 pb-8 w-full max-md:px-5 max-md:max-w-full">
      <nav className="flex justify-between items-start p-5 w-full text-base text-white border-t border-b border-white border-opacity-60 max-md:max-w-full">
        <div className="flex gap-10 items-start min-w-[240px] max-md:max-w-full">
          <a href="#inicio">Inicio</a>
          <a href="#sobre">Sobre Nós</a>
          <a href="#servicos">Serviços</a>
          <a href="#portfolio">Portfolio</a>
          <a href="#contato">Contacte-nos</a>
        </div>
      </nav>
      <div className="flex flex-wrap gap-10 justify-between items-center mt-8 w-full max-md:max-w-full">
        <div className="flex flex-col self-stretch my-auto text-white min-w-[240px] w-[370px]">
          <Logo />
          <p className="mt-2.5 text-sm leading-6">
            Lörem ipsum od ohet dilogi. Bell trabel, samuligt, ohöbel utom
            diska. Jinesade bel när feras redorade i belogi. FAR paratyp i
            muvåning, och pesask vyfisat. Viktiga poddradio har un mad och inde.
          </p>
        </div>
        <ContactInfo />
        <SocialLinks />
      </div>
      <div className="flex pt-8 mt-8 w-full border-t border-white border-opacity-60 min-h-[52px] max-md:max-w-full" />
    </footer>
  );
};

export default Footer;
