/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation: React.FC = () => {
  const navItems = ["Inicio", "Sobre", "Projetos", "Contatos"];

  return (
    <nav className="flex gap-10 items-center self-stretch my-auto text-sm font-bold leading-none text-white whitespace-nowrap min-w-[240px] w-[344px]">
      {navItems.map((item, index) => (
        <a
          key={index}
          href={`#${item.toLowerCase()}`}
          className="self-stretch my-auto"
        >
          {item}
        </a>
      ))}
    </nav>
  );
};

export default Navigation;
